### ISSUE TITLE
Startup script runs in FPE> prompt

### ISSUE THREAD

**Issue by TESSUser** [TESScience/fpe_tessting#1]
When running a python script intended to initialize and run FPE wrapper 6.4.1 (with ObsSim 1.7b), commands which should go to the shell are instead executed inside the "FPE1>" prompt.  The script, "tempload.py", at present, looks like this:

if **name** == "**main**":
    from tessfpe.dhu.fpe import FPE
    from tessfpe.dhu.unit_tests import check_house_keeping_voltages
    from sys import argv
    assert argv[1] in ['6.1.1', '6.0.5772', '6.1t.1', '6.1.4', '6.1t.4']
    fpe1 = FPE(1, debug=True, preload=True, FPE_Wrapper_version=argv[1])
    print fpe1.version
    if check_house_keeping_voltages(fpe1):
        print "Wrapper load complete. Interface voltages OK."
    else: print "Load failure." 

The terminal output in response to this script looks like this:

[tess@CALADAN fpe_tessting]$ ./tempload.py 6.1.4
FPE1>  Running:
tftp <<EOF
mode binary
connect 192.168.100.1 69
put /home/tess/Desktop/FPE/tessfpe/dhu/MemFiles/FPE_Wrapper-6.1.4.bin bitmem 
EOF
Sending 575276 words to FPE Bit memory from bitmem
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . FPGA Load complete
Running:
tftp <<EOF
mode binary
connect 192.168.100.1 69
put /home/tess/Desktop/FPE/tessfpe/dhu/MemFiles/Reg.bin regmem 
EOF
FPE1>  Sending 32 bytes to FPE Registers
FPE Register Load complete
Running:
tftp <<EOF
mode binary
connect 192.168.100.1 69
put /tmp/tmp_9mjmaHskMem.bin hskmem 
EOF
FPE1>  Adjusting transfer length to nearest word boundary
Sending 129 words to HSK Voltage memory from hskmem
Housekeeping Memory Load complete
Running:
tftp <<EOF
mode binary
connect 192.168.100.1 69
put /tmp/tmpSfS1mtCLVMem.bin clvmem 
EOF
FPE1>  Sending 64 words to FPE Voltage memory from clvmem
Voltage Memory Load complete
Running:
tftp <<EOF
mode binary
connect 192.168.100.1 69
put /tmp/tmpyrhe_KSeqMem.bin seqmem 
EOF
FPE1>  Sending 2048 words to FPE Sequencer memory from seqmem
Sequence Memory Load complete
Running:
tftp <<EOF
mode binary
connect 192.168.100.1 69
put /tmp/tmpiX1LFePrgMem.bin prgmem 
EOF
FPE1>  Sending 1024 words to FPE Program memory from prgmem
Program Memory Load complete
FPE1>  Starting frames...
FPE1>  Frames Stopped...
FPE1> 
Traceback (most recent call last):
  File "./tempload.py", line 15, in <module>
    fpe1 = FPE(1, debug=True, preload=True, FPE_Wrapper_version=argv[1])
  File "/home/tess/Desktop/fpe_tessting/tessfpe/dhu/fpe.py", line 48, in **init**
    check_house_keeping_voltages(self)
  File "/home/tess/Desktop/fpe_tessting/tessfpe/dhu/unit_tests/**init**.py", line 21, in check_house_keeping_voltages
    hsk = fpe.house_keeping
  File "/home/tess/Desktop/fpe_tessting/tessfpe/dhu/fpe.py", line 179, in house_keeping
    hsk = self.cmd_cam_hsk()
  File "/home/tess/Desktop/fpe_tessting/tessfpe/dhu/fpe.py", line 130, in cmd_cam_hsk
    matches=channels
  File "/home/tess/Desktop/fpe_tessting/tessfpe/dhu/fpesocketconnection.py", line 68, in send_command
    raise t
tessfpe.dhu.fpesocketconnection.TimeOutError: Timeout on trial 10
[tess@CALADAN fpe_tessting]$

**Comment by TESSUser** [comment]
Wait - is it _supposed_ to do that when Debug=True?  Is the only problem really the Timeout at the end?

**Comment by TESSUser** [comment]
When I comment out the last few statements of the tempload.py, like this:

if **name** == "**main**":
    from tessfpe.dhu.fpe import FPE
    from tessfpe.dhu.unit_tests import check_house_keeping_voltages
    from sys import argv
    assert argv[1] in ['6.1.1', '6.0.5772', '6.1t.1', '6.1.4', '6.1t.4']
    fpe1 = FPE(1, debug=True, preload=True, FPE_Wrapper_version=argv[1])
(#    print fpe1.version) Ed.: parens to keep GitHub from formatting strangely
(#    if check_house_keeping_voltages(fpe1):)
(#        print "Wrapper load complete. Interface voltages OK.")
(#    else: print "Load failure.")

I get different behavior in the terminal window, which suggests the wrapper has successfully loaded.  It looks like this:

[tess@CALADAN fpe_tessting]$ ./tempload.py 6.1.4
FPE1>  Running:
tftp <<EOF
mode binary
connect 192.168.100.1 69
put /home/tess/Desktop/FPE/tessfpe/dhu/MemFiles/FPE_Wrapper-6.1.4.bin bitmem 
EOF
Sending 575276 words to FPE Bit memory from bitmem
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . FPGA Load complete
Running:
tftp <<EOF
mode binary
connect 192.168.100.1 69
put /home/tess/Desktop/FPE/tessfpe/dhu/MemFiles/Reg.bin regmem 
EOF
FPE1>  Sending 32 bytes to FPE Registers
FPE Register Load complete
Running:
tftp <<EOF
mode binary
connect 192.168.100.1 69
put /tmp/tmpsgs_zAHskMem.bin hskmem 
EOF
FPE1>  Adjusting transfer length to nearest word boundary
Sending 129 words to HSK Voltage memory from hskmem
Housekeeping Memory Load complete
Running:
tftp <<EOF
mode binary
connect 192.168.100.1 69
put /tmp/tmpWIuglnCLVMem.bin clvmem 
EOF
FPE1>  Sending 64 words to FPE Voltage memory from clvmem
Voltage Memory Load complete
Running:
tftp <<EOF
mode binary
connect 192.168.100.1 69
put /tmp/tmpMmDCZcSeqMem.bin seqmem 
EOF
FPE1>  Sending 2048 words to FPE Sequencer memory from seqmem
Sequence Memory Load complete
Running:
tftp <<EOF
mode binary
connect 192.168.100.1 69
put /tmp/tmpZFd8K1PrgMem.bin prgmem 
EOF
FPE1>  Sending 1024 words to FPE Program memory from prgmem
Program Memory Load complete
FPE1>  Starting frames...
FPE1>  Frames Stopped...
FPE1>  Hsk[0] = 0x00180000
Hsk[1] = 0x07ed07f0
Hsk[2] = 0x07ed07ee
Hsk[3] = 0xa2b1ffe3
Hsk[4] = 0x3e1597fb
Hsk[5] = 0xa1d8a1ae
Hsk[6] = 0x0001a1d4
Hsk[7] = 0xa262ffff
Hsk[8] = 0x000807ef
Hsk[9] = 0x00050008
Hsk[10] = 0x08051731
Hsk[11] = 0x16d4a338
Hsk[12] = 0xa284ffdd
Hsk[13] = 0x3e509698
Hsk[14] = 0xa1b8a211
Hsk[15] = 0xa28fa2df
Hsk[16] = 0x00000005
Hsk[17] = 0x00101388
Hsk[18] = 0x00800020
Hsk[19] = 0x00010000
Hsk[20] = 0x00000000
Hsk[21] = 0x001b0000
Hsk[22] = 0x00000000
Hsk[23] = 0xc00807cc
Hsk[24] = 0x00000000
Hsk[25] = 0x00180019
Hsk[26] = 0x969aa1bd
Hsk[27] = 0xa211a28e
Hsk[28] = 0xa2dd0003
Hsk[29] = 0x00060006
Hsk[30] = 0x000707ef
Hsk[31] = 0x17031701
Hsk[32] = 0xa20fa1ac
Hsk[33] = 0xfffe3d8a
Hsk[34] = 0x97f8a10b
Hsk[35] = 0xa1b9a1bf
Hsk[36] = 0xa1f50000
Hsk[37] = 0x00050006
Hsk[38] = 0x00060829
Hsk[39] = 0x17021761
Hsk[40] = 0xa2d1a280
Hsk[41] = 0x00013dcf
Hsk[42] = 0x00101388
Hsk[43] = 0x00800020
Hsk[44] = 0x00010000
Hsk[45] = 0x00000000
Hsk[46] = 0x001d0000
Hsk[47] = 0x00000001
Hsk[48] = 0xc00807cc
Hsk[49] = 0x00000000
Hsk[50] = 0x00000000
Hsk[51] = 0x00000000
Hsk[52] = 0x00000000
Hsk[53] = 0x00000000
Hsk[54] = 0x00000000
Hsk[55] = 0x00000000
Hsk[56] = 0x00000000
Hsk[57] = 0x00180039
Hsk[58] = 0x97a1a1db
Hsk[59] = 0xa1f2a1d8
Hsk[60] = 0xa2440000
Hsk[61] = 0x00070006
Hsk[62] = 0x000438e2
Hsk[63] = 0x3d5ae08b
Hsk[64] = 0x0ebce97b
Hsk[65] = 0x00bea2de
Hsk[66] = 0xa30b38ed
Hsk[67] = 0x3e1be12d
Hsk[68] = 0x0fcbe91e
Hsk[69] = 0x008ea248
Hsk[70] = 0xa3933953
Hsk[71] = 0x3e69e0af
Hsk[72] = 0x0f32e80b
Hsk[73] = 0xffa7a369
Hsk[74] = 0x00101388
Hsk[75] = 0x00800020
Hsk[76] = 0x00010000
Hsk[77] = 0x00000000
Hsk[78] = 0x001d0000
Hsk[79] = 0x00000001
Hsk[80] = 0xc00807cc
Hsk[81] = 0x00000000
Hsk[82] = 0x00000000
Hsk[83] = 0x00000000
Hsk[84] = 0x00000000
Hsk[85] = 0x00000000
Hsk[86] = 0x00000000
Hsk[87] = 0x00000000
Hsk[88] = 0x00000000
Hsk[89] = 0x00180059
Hsk[90] = 0xa3ae38e6
Hsk[91] = 0x3e93e111
Hsk[92] = 0x0fe7e8c5
Hsk[93] = 0x0007a397
Hsk[94] = 0xa26dff16
Hsk[95] = 0xff89ff85
Hsk[96] = 0x00180079
Hsk[97] = 0x2eec3154
Hsk[98] = 0x4e7f7e61
Hsk[99] = 0x19507fff
Hsk[100] = 0x7fff07f0
Hsk[101] = 0x07ee07ee
Hsk[102] = 0x07eea2ad
Hsk[103] = 0xffe03e14
Hsk[104] = 0x97fca1d5
Hsk[105] = 0xa1ae0000
Hsk[106] = 0xa1d7a25f
Hsk[107] = 0x00020005
Hsk[108] = 0x07ee0007
Hsk[109] = 0x00080805
Hsk[110] = 0x173516d2
Hsk[111] = 0xa336a283
Hsk[112] = 0xffdc3e50
Hsk[113] = 0x00101388
Hsk[114] = 0x00800020
Hsk[115] = 0x00010000
Hsk[116] = 0x00000000
Hsk[117] = 0x001d0000
Hsk[118] = 0x00000001
Hsk[119] = 0xc00807cc
Hsk[120] = 0x00000000
Hsk[121] = 0x00000000
Hsk[122] = 0x00000000
Hsk[123] = 0x00000000
Hsk[124] = 0x00000000
Hsk[125] = 0x00000000
Hsk[126] = 0x00000000
Hsk[127] = 0x00000000
Traceback (most recent call last):
  File "./tempload.py", line 15, in <module>
    fpe1 = FPE(1, debug=True, preload=True, FPE_Wrapper_version=argv[1])
  File "/home/tess/Desktop/fpe_tessting/tessfpe/dhu/fpe.py", line 48, in **init**
    check_house_keeping_voltages(self)
  File "/home/tess/Desktop/fpe_tessting/tessfpe/dhu/unit_tests/**init**.py", line 28, in check_house_keeping_voltages
    actual=hsk["analogue"][key]))
Exception: Housekeeping value for +1.8f should be 1.8, was 13.4082641602
[tess@CALADAN fpe_tessting]$
